In [1]:
# Dependencies and Setup
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

file_to_load = "data/data.csv"

data = pd.read_csv(file_to_load)
data.head()

,case_no,number_killed,number_injured,location,state,shooter_last_name,shooter_first_name,full_date,day_of_week,day,...,race,education,relationship_status,specify_relationship_to_other_shootings,total_weapons_brought_to_the_scene,crime_violence_confact_pct,trauma_crisis_confact_pct,mental_health_confact_pct,motivation_confact_pct,social_contagion_confact_pct
0,2,4,0,Workplace,New York,White,Joseph,9/23/1970,Wednesday,23,...,White,Graduate School/Degree,Single,NaN,1,0.00%,37.50%,25.00%,26.67%,28.57%
1,3,4,1,Other,Pennsylvania,Belmonte,Victor,7/21/1980,Monday,21,...,White,College/Trade School,Single,NaN,1,0.00%,37.50%,12.50%,6.67%,14.29%
2,4,4,1,Retail,Pennsylvania,O'Brien Smith,Timothy,1/28/2018,Sunday,28,...,White,College/Trade School,Single,NaN,3,14.29%,25.00%,12.50%,13.33%,28.57%
3,5,4,17,Other,Pennsylvania,Lambright,Donald,4/5/1969,Saturday,5,...,Black,College/Trade School,Married,NaN,3,0.00%,50.00%,25.00%,26.67%,14.29%
4,6,32,26,College/University,Virginia,Cho,Seung-Hui,4/16/2007,Monday,16,...,Asian,College/Trade School,Single,He referenced Columbine and did the shooting i...,2,28.57%,37.50%,100.00%,13.33%,100.00%

In [2]:
sm_data=data.loc[:,["number_killed", "number_injured", "full_date",  
                   "day", "month", "year", "city", "state", "location", "urbansuburbanrural", "age", "gender", "education",
                   "relationship_status", "crime_violence_confact_pct", "trauma_crisis_confact_pct", 
                   "mental_health_confact_pct", "motivation_confact_pct", "social_contagion_confact_pct"]]
sm_data

,number_killed,number_injured,full_date,day,month,year,city,state,location,urbansuburbanrural,age,gender,education,relationship_status,crime_violence_confact_pct,trauma_crisis_confact_pct,mental_health_confact_pct,motivation_confact_pct,social_contagion_confact_pct
0,4,0,9/23/1970,23,9,1970,Albany,New York,Workplace,Urban,25,Male,Graduate School/Degree,Single,0.00%,37.50%,25.00%,26.67%,28.57%
1,4,1,7/21/1980,21,7,1980,Coraopolis,Pennsylvania,Other,Suburban,23,Male,College/Trade School,Single,0.00%,37.50%,12.50%,6.67%,14.29%
2,4,1,1/28/2018,28,1,2018,Saltlick Township,Pennsylvania,Retail,Rural,28,Male,College/Trade School,Single,14.29%,25.00%,12.50%,13.33%,28.57%
3,4,17,4/5/1969,5,4,1969,Harrisburg,Pennsylvania,Other,Urban,31,Male,College/Trade School,Married,0.00%,50.00%,25.00%,26.67%,14.29%
4,32,26,4/16/2007,16,4,2007,Blacksburg,Virginia,College/University,Rural,23,Male,College/Trade School,Single,28.57%,37.50%,100.00%,13.33%,100.00%
5,5,1,12/31/1994,31,12,1994,"Raeford, Hoke County, NC",North Carolina,Retail,Rural,18,Male,<High School,Single,28.57%,12.50%,25.00%,6.67%,28.57%
6,8,1,5/17/1984,17,5,1984,Manley Hot Springs,Alaska,Other,Rural,25,Male,High School/GED,Single,57.14%,0.00%,0.00%,13.33%,14.29%
7,4,0,11/9/1991,9,11,1991,Harrodsburg,Kentucky,Other,Rural,45,Male,NaN,Divorced/Separated/Widowed,28.57%,25.00%,50.00%,13.33%,28.57%
8,5,3,10/16/1981,16,10,1981,Allen,Kentucky,Retail,Rural,70,Male,NaN,Single,42.86%,0.00%,12.50%,20.00%,14.29%
9,7,1,8/7/2011,7,8,2011,Copley Township,Ohio,Other,Suburban,51,Male,High School/GED,Boyfriend/Girlfriend,0.00%,37.50%,25.00%,6.67%,0.00%
10,6,2,11/21/2004,21,11,2004,Birchwood,Wisconsin,Other,Rural,36,Male,High School/GED,Married,28.57%,50.00%,0.00%,13.33%,0.00%
11,5,2,11/12/1966,12,11,1966,Mesa,Arizona,Retail,Urban,18,Male,<High School,Single,0.00%,37.50%,25.00%,13.33%,71.43%
12,6,0,11/14/2015,14,11,2015,Tennessee Colony,Texas,Other,Rural,33,Male,High School/GED,Divorced/Separated/Widowed,57.14%,37.50%,50.00%,6.67%,0.00%
13,6,1,6/29/1984,29,6,1984,Dallas,Texas,Restaurant/Bar/Nightclub,Urban,39,Male,<High School,Divorced/Separated/Widowed,28.57%,37.50%,62.50%,20.00%,28.57%
14,6,0,10/11/1983,11,10,1983,College Station,Texas,Other,Suburban,24,Male,<High School,Divorced/Separated/Widowed,14.29%,25.00%,12.50%,6.67%,14.29%
15,7,23,8/31/2019,31,8,2019,Odessa,Texas,Other,Urban,36,Male,College/Trade School,NaN,28.57%,25.00%,50.00%,6.67%,14.29%
16,5,3,6/7/2013,7,6,2013,Santa Monica,California,College/University,Urban,23,Male,College/Trade School,Single,42.86%,25.00%,37.50%,6.67%,14.29%
17,7,3,4/2/2012,2,4,2012,Oakland,California,College/University,Urban,43,Male,College/Trade School,Single,14.29%,37.50%,25.00%,6.67%,0.00%
18,4,20,5/7/1981,7,5,1981,Salem,Oregon,Restaurant/Bar/Nightclub,Urban,25,Male,NaN,Single,0.00%,12.50%,12.50%,6.67%,14.29%
19,4,0,5/3/1982,3,5,1982,Anchorage,Alaska,Other,Urban,34,Male,College/Trade School,Single,42.86%,0.00%,62.50%,6.67%,14.29%
20,6,2,3/1/1983,1,3,1983,McCarthy,Alaska,Other,Rural,39,Male,NaN,Divorced/Separated/Widowed,14.29%,25.00%,50.00%,6.67%,28.57%
21,7,0,12/26/2000,26,12,2000,Wakefield,Massachusett,Workplace,Suburban,42,Male,College/Trade School,Boyfriend/Girlfriend,28.57%,37.50%,87.50%,20.00%,28.57%
22,5,0,6/17/1978,17,6,1978,Warwick,Rhode Island,Workplace,Urban,48,Male,NaN,Married,0.00%,12.50%,12.50%,13.33%,14.29%
23,4,4,8/19/1997,19,8,1997,Colebrook,New Hampshire,Other,Rural,62,Male,NaN,Divorced/Separated/Widowed,57.14%,25.00%,12.50%,6.67%,14.29%
24,8,2,8/3/2010,3,8,2010,Manchester,Connecticut,Workplace,Suburban,34,Male,College/Trade School,Boyfriend/Girlfriend,0.00%,37.50%,12.50%,20.00%,14.29%
25,4,0,3/6/1998,6,3,1998,Newington,Connecticut,Workplace,Suburban,35,Male,Bachelor's Degree,Single,14.29%,37.50%,75.00%,6.67%,14.29%
26,27,1,12/14/2012,14,12,2012,Newtown,Connecticut,K-12 school,Suburban,20,Male,College/Trade School,Single,28.57%,37.50%,50.00%,13.33%,42.86%
27,4,0,10/10/1991,10,10,1991,Ridgewood,New Jersey,Workplace,Suburban,35,Male,NaN,Single,71.43%,25.00%,25.00%,6.67%,85.71%
28,6,0,8/26/1977,26,8,1977,Hackettstown,New Jersey,Other,Rural,20,Male,NaN,Single,28.57%,25.00%,50.00%,13.33%,14.29%
29,6,6,6/21/1972,21,6,1972,Cherry Hill,New Jersey,Workplace,Suburban,33,Male,College/Trade School,NaN,14.29%,12.50%,12.50%,6.67%,14.29%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,14,22,12/2/2015,2,12,2015,San Bernardino,California,Workplace,Urban,28,Male,Graduate School/Degree,Married,14.29%,12.50%,12.50%,6.67%,57.14%
142,7,2,7/12/1976,12,7,1976,Fullerton,California,College/University,Urban,37,Male,NaN,Divorced/Separated/Widowed,28.57%,37.50%,37.50%,6.67%,14.29%
143,4,3,12/19/1997,19,12,1997,Orange,California,Workplace,Suburban,41,Male,High School/GED,Married,14.29%,25.00%,25.00%,13.33%,14.29%
144,4,5,12/2/1993,2,12,1993,Oxnard,California,Workplace,Suburban,33,Male,Bachelor's Degree,Single,0.00%,50.00%,25.00%,13.33%,28.57%
145,6,14,5/23/2014,23,5,2014,Isla Vista,California,College/University,Suburban,22,Male,College/Trade School,Single,28.57%,37.50%,75.00%,26.67%,85.71%
146,7,0,1/30/2006,30,1,2006,Goleta,California,Workplace,Suburban,44,Female,NaN,Single,14.29%,12.50%,37.50%,20.00%,14.29%
147,5,0,9/12/2018,12,9,2018,Bakersfield,California,Workplace,Urban,54,Male,NaN,Divorced/Separated/Widowed,0.00%,25.00%,12.50%,13.33%,0.00%
148,6,1,11/8/1992,8,11,1992,Morro Bay,California,Other,Suburban,43,Male,NaN,Divorced/Separated/Widowed,28.57%,25.00%,25.00%,20.00%,42.86%
149,4,0,3/18/2008,18,3,2008,Santa Maria,California,Workplace,Urban,31,Male,High School/GED,Single,28.57%,50.00%,37.50%,6.67%,14.29%
150,7,4,2/16/1988,16,2,1988,Sunnyvale,California,Workplace,Urban,39,Male,College/Trade School,Boyfriend/Girlfriend,57.14%,12.50%,25.00%,20.00%,57.14%
151,8,6,7/1/1993,1,7,1993,San Francisco,California,Other,Urban,55,Male,Graduate School/Degree,Divorced/Separated/Widowed,0.00%,25.00%,25.00%,20.00%,28.57%
152,5,30,1/17/1989,17,1,1989,Stockton,California,K-12 school,Rural,24,Male,College/Trade School,Single,42.86%,50.00%,87.50%,20.00%,57.14%
153,5,1,3/2/1975,2,3,1975,Smith River,California,Other,Rural,21,Male,NaN,Single,28.57%,62.50%,25.00%,6.67%,14.29%
154,4,4,4/22/2018,22,4,2018,Nashville,Tennessee,Restaurant/Bar/Nightclub,Urban,29,Male,High School/GED,Single,42.86%,25.00%,37.50%,6.67%,0.00%
155,5,2,9/8/2001,8,9,2001,Sacramento,California,Workplace,Urban,20,Male,High School/GED,Single,14.29%,50.00%,25.00%,26.67%,71.43%
156,4,10,5/1/1992,1,5,1992,Olivehurst,California,K-12 school,Rural,20,Male,<High School,Single,14.29%,62.50%,37.50%,33.33%,71.43%
157,5,12,11/14/2017,14,11,2017,Rancho Tehama Reserve,California,Other,Rural,44,Male,College/Trade School,Married,57.14%,12.50%,37.50%,20.00%,14.29%
158,4,2,2/20/2014,20,2,2014,Alturas,California,Building/Place of Civic Importance,Rural,44,Female,NaN,Single,28.57%,25.00%,0.00%,20.00%,0.00%
159,7,0,11/2/1999,2,11,1999,Honolulu,Hawaii,Workplace,Urban,40,Male,College/Trade School,Single,57.14%,37.50%,50.00%,13.33%,14.29%
160,9,7,10/1/2015,1,10,2015,Roseburg,Oregon,College/University,Rural,26,Male,College/Trade School,Single,28.57%,12.50%,50.00%,26.67%,85.71%
161,4,25,5/20/1998,20,5,1998,Springfield,Oregon,K-12 school,Suburban,15,Male,<High School,Single,57.14%,37.50%,50.00%,20.00%,71.43%
162,6,2,7/23/1977,23,7,1977,Klamath Falls,Oregon,Restaurant/Bar/Nightclub,Rural,26,Male,NaN,Divorced/Separated/Widowed,0.00%,37.50%,37.50%,6.67%,28.57%
163,4,0,4/21/2013,21,4,2013,Federal Way,Washington,Other,Urban,27,Male,College/Trade School,Boyfriend/Girlfriend,28.57%,12.50%,0.00%,13.33%,0.00%
164,5,1,5/30/2012,30,5,2012,Seattle,Washington,Restaurant/Bar/Nightclub,Urban,40,Male,High School/GED,Boyfriend/Girlfriend,57.14%,12.50%,62.50%,6.67%,14.29%
165,6,2,3/25/2006,25,3,2006,Seattle,Washington,Other,Urban,28,Male,College/Trade School,Single,42.86%,12.50%,37.50%,6.67%,57.14%
166,5,0,9/23/2016,23,9,2016,Burlington,Washington,Retail,Suburban,20,Male,High School/GED,Single,71.43%,37.50%,75.00%,13.33%,42.86%
167,4,1,10/24/2014,24,10,2014,Marysville,Washington,K-12 school,Urban,15,Male,<High School,Boyfriend/Girlfriend,42.86%,37.50%,25.00%,6.67%,57.14%
168,6,4,9/2/2008,2,9,2008,Alger,Washington,Other,Rural,28,Male,NaN,Single,28.57%,37.50%,62.50%,6.67%,14.29%
169,4,0,11/29/2009,29,11,2009,Parkland,Washington,Restaurant/Bar/Nightclub,Suburban,37,Male,<High School,Married,28.57%,50.00%,37.50%,26.67%,14.29%
170,4,23,6/20/1994,20,6,1994,Spokane,Washington,Workplace,Urban,20,Male,College/Trade School,Single,0.00%,37.50%,37.50%,13.33%,28.57%

In [3]:
sm_data=data.loc[:,["number_killed", "number_injured", "full_date",  
                   "day", "month", "year", "city", "state", "location", "urbansuburbanrural", "age", "gender", "education",
                   "relationship_status", "crime_violence_confact_pct", "trauma_crisis_confact_pct", 
                   "mental_health_confact_pct", "motivation_confact_pct", "social_contagion_confact_pct"]]
sm_data

,number_killed,number_injured,full_date,day,month,year,city,state,location,urbansuburbanrural,age,gender,education,relationship_status,crime_violence_confact_pct,trauma_crisis_confact_pct,mental_health_confact_pct,motivation_confact_pct,social_contagion_confact_pct
0,4,0,9/23/1970,23,9,1970,Albany,New York,Workplace,Urban,25,Male,Graduate School/Degree,Single,0.00%,37.50%,25.00%,26.67%,28.57%
1,4,1,7/21/1980,21,7,1980,Coraopolis,Pennsylvania,Other,Suburban,23,Male,College/Trade School,Single,0.00%,37.50%,12.50%,6.67%,14.29%
2,4,1,1/28/2018,28,1,2018,Saltlick Township,Pennsylvania,Retail,Rural,28,Male,College/Trade School,Single,14.29%,25.00%,12.50%,13.33%,28.57%
3,4,17,4/5/1969,5,4,1969,Harrisburg,Pennsylvania,Other,Urban,31,Male,College/Trade School,Married,0.00%,50.00%,25.00%,26.67%,14.29%
4,32,26,4/16/2007,16,4,2007,Blacksburg,Virginia,College/University,Rural,23,Male,College/Trade School,Single,28.57%,37.50%,100.00%,13.33%,100.00%
5,5,1,12/31/1994,31,12,1994,"Raeford, Hoke County, NC",North Carolina,Retail,Rural,18,Male,<High School,Single,28.57%,12.50%,25.00%,6.67%,28.57%
6,8,1,5/17/1984,17,5,1984,Manley Hot Springs,Alaska,Other,Rural,25,Male,High School/GED,Single,57.14%,0.00%,0.00%,13.33%,14.29%
7,4,0,11/9/1991,9,11,1991,Harrodsburg,Kentucky,Other,Rural,45,Male,NaN,Divorced/Separated/Widowed,28.57%,25.00%,50.00%,13.33%,28.57%
8,5,3,10/16/1981,16,10,1981,Allen,Kentucky,Retail,Rural,70,Male,NaN,Single,42.86%,0.00%,12.50%,20.00%,14.29%
9,7,1,8/7/2011,7,8,2011,Copley Township,Ohio,Other,Suburban,51,Male,High School/GED,Boyfriend/Girlfriend,0.00%,37.50%,25.00%,6.67%,0.00%
10,6,2,11/21/2004,21,11,2004,Birchwood,Wisconsin,Other,Rural,36,Male,High School/GED,Married,28.57%,50.00%,0.00%,13.33%,0.00%
11,5,2,11/12/1966,12,11,1966,Mesa,Arizona,Retail,Urban,18,Male,<High School,Single,0.00%,37.50%,25.00%,13.33%,71.43%
12,6,0,11/14/2015,14,11,2015,Tennessee Colony,Texas,Other,Rural,33,Male,High School/GED,Divorced/Separated/Widowed,57.14%,37.50%,50.00%,6.67%,0.00%
13,6,1,6/29/1984,29,6,1984,Dallas,Texas,Restaurant/Bar/Nightclub,Urban,39,Male,<High School,Divorced/Separated/Widowed,28.57%,37.50%,62.50%,20.00%,28.57%
14,6,0,10/11/1983,11,10,1983,College Station,Texas,Other,Suburban,24,Male,<High School,Divorced/Separated/Widowed,14.29%,25.00%,12.50%,6.67%,14.29%
15,7,23,8/31/2019,31,8,2019,Odessa,Texas,Other,Urban,36,Male,College/Trade School,NaN,28.57%,25.00%,50.00%,6.67%,14.29%
16,5,3,6/7/2013,7,6,2013,Santa Monica,California,College/University,Urban,23,Male,College/Trade School,Single,42.86%,25.00%,37.50%,6.67%,14.29%
17,7,3,4/2/2012,2,4,2012,Oakland,California,College/University,Urban,43,Male,College/Trade School,Single,14.29%,37.50%,25.00%,6.67%,0.00%
18,4,20,5/7/1981,7,5,1981,Salem,Oregon,Restaurant/Bar/Nightclub,Urban,25,Male,NaN,Single,0.00%,12.50%,12.50%,6.67%,14.29%
19,4,0,5/3/1982,3,5,1982,Anchorage,Alaska,Other,Urban,34,Male,College/Trade School,Single,42.86%,0.00%,62.50%,6.67%,14.29%
20,6,2,3/1/1983,1,3,1983,McCarthy,Alaska,Other,Rural,39,Male,NaN,Divorced/Separated/Widowed,14.29%,25.00%,50.00%,6.67%,28.57%
21,7,0,12/26/2000,26,12,2000,Wakefield,Massachusett,Workplace,Suburban,42,Male,College/Trade School,Boyfriend/Girlfriend,28.57%,37.50%,87.50%,20.00%,28.57%
22,5,0,6/17/1978,17,6,1978,Warwick,Rhode Island,Workplace,Urban,48,Male,NaN,Married,0.00%,12.50%,12.50%,13.33%,14.29%
23,4,4,8/19/1997,19,8,1997,Colebrook,New Hampshire,Other,Rural,62,Male,NaN,Divorced/Separated/Widowed,57.14%,25.00%,12.50%,6.67%,14.29%
24,8,2,8/3/2010,3,8,2010,Manchester,Connecticut,Workplace,Suburban,34,Male,College/Trade School,Boyfriend/Girlfriend,0.00%,37.50%,12.50%,20.00%,14.29%
25,4,0,3/6/1998,6,3,1998,Newington,Connecticut,Workplace,Suburban,35,Male,Bachelor's Degree,Single,14.29%,37.50%,75.00%,6.67%,14.29%
26,27,1,12/14/2012,14,12,2012,Newtown,Connecticut,K-12 school,Suburban,20,Male,College/Trade School,Single,28.57%,37.50%,50.00%,13.33%,42.86%
27,4,0,10/10/1991,10,10,1991,Ridgewood,New Jersey,Workplace,Suburban,35,Male,NaN,Single,71.43%,25.00%,25.00%,6.67%,85.71%
28,6,0,8/26/1977,26,8,1977,Hackettstown,New Jersey,Other,Rural,20,Male,NaN,Single,28.57%,25.00%,50.00%,13.33%,14.29%
29,6,6,6/21/1972,21,6,1972,Cherry Hill,New Jersey,Workplace,Suburban,33,Male,College/Trade School,NaN,14.29%,12.50%,12.50%,6.67%,14.29%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,14,22,12/2/2015,2,12,2015,San Bernardino,California,Workplace,Urban,28,Male,Graduate School/Degree,Married,14.29%,12.50%,12.50%,6.67%,57.14%
142,7,2,7/12/1976,12,7,1976,Fullerton,California,College/University,Urban,37,Male,NaN,Divorced/Separated/Widowed,28.57%,37.50%,37.50%,6.67%,14.29%
143,4,3,12/19/1997,19,12,1997,Orange,California,Workplace,Suburban,41,Male,High School/GED,Married,14.29%,25.00%,25.00%,13.33%,14.29%
144,4,5,12/2/1993,2,12,1993,Oxnard,California,Workplace,Suburban,33,Male,Bachelor's Degree,Single,0.00%,50.00%,25.00%,13.33%,28.57%
145,6,14,5/23/2014,23,5,2014,Isla Vista,California,College/University,Suburban,22,Male,College/Trade School,Single,28.57%,37.50%,75.00%,26.67%,85.71%
146,7,0,1/30/2006,30,1,2006,Goleta,California,Workplace,Suburban,44,Female,NaN,Single,14.29%,12.50%,37.50%,20.00%,14.29%
147,5,0,9/12/2018,12,9,2018,Bakersfield,California,Workplace,Urban,54,Male,NaN,Divorced/Separated/Widowed,0.00%,25.00%,12.50%,13.33%,0.00%
148,6,1,11/8/1992,8,11,1992,Morro Bay,California,Other,Suburban,43,Male,NaN,Divorced/Separated/Widowed,28.57%,25.00%,25.00%,20.00%,42.86%
149,4,0,3/18/2008,18,3,2008,Santa Maria,California,Workplace,Urban,31,Male,High School/GED,Single,28.57%,50.00%,37.50%,6.67%,14.29%
150,7,4,2/16/1988,16,2,1988,Sunnyvale,California,Workplace,Urban,39,Male,College/Trade School,Boyfriend/Girlfriend,57.14%,12.50%,25.00%,20.00%,57.14%
151,8,6,7/1/1993,1,7,1993,San Francisco,California,Other,Urban,55,Male,Graduate School/Degree,Divorced/Separated/Widowed,0.00%,25.00%,25.00%,20.00%,28.57%
152,5,30,1/17/1989,17,1,1989,Stockton,California,K-12 school,Rural,24,Male,College/Trade School,Single,42.86%,50.00%,87.50%,20.00%,57.14%
153,5,1,3/2/1975,2,3,1975,Smith River,California,Other,Rural,21,Male,NaN,Single,28.57%,62.50%,25.00%,6.67%,14.29%
154,4,4,4/22/2018,22,4,2018,Nashville,Tennessee,Restaurant/Bar/Nightclub,Urban,29,Male,High School/GED,Single,42.86%,25.00%,37.50%,6.67%,0.00%
155,5,2,9/8/2001,8,9,2001,Sacramento,California,Workplace,Urban,20,Male,High School/GED,Single,14.29%,50.00%,25.00%,26.67%,71.43%
156,4,10,5/1/1992,1,5,1992,Olivehurst,California,K-12 school,Rural,20,Male,<High School,Single,14.29%,62.50%,37.50%,33.33%,71.43%
157,5,12,11/14/2017,14,11,2017,Rancho Tehama Reserve,California,Other,Rural,44,Male,College/Trade School,Married,57.14%,12.50%,37.50%,20.00%,14.29%
158,4,2,2/20/2014,20,2,2014,Alturas,California,Building/Place of Civic Importance,Rural,44,Female,NaN,Single,28.57%,25.00%,0.00%,20.00%,0.00%
159,7,0,11/2/1999,2,11,1999,Honolulu,Hawaii,Workplace,Urban,40,Male,College/Trade School,Single,57.14%,37.50%,50.00%,13.33%,14.29%
160,9,7,10/1/2015,1,10,2015,Roseburg,Oregon,College/University,Rural,26,Male,College/Trade School,Single,28.57%,12.50%,50.00%,26.67%,85.71%
161,4,25,5/20/1998,20,5,1998,Springfield,Oregon,K-12 school,Suburban,15,Male,<High School,Single,57.14%,37.50%,50.00%,20.00%,71.43%
162,6,2,7/23/1977,23,7,1977,Klamath Falls,Oregon,Restaurant/Bar/Nightclub,Rural,26,Male,NaN,Divorced/Separated/Widowed,0.00%,37.50%,37.50%,6.67%,28.57%
163,4,0,4/21/2013,21,4,2013,Federal Way,Washington,Other,Urban,27,Male,College/Trade School,Boyfriend/Girlfriend,28.57%,12.50%,0.00%,13.33%,0.00%
164,5,1,5/30/2012,30,5,2012,Seattle,Washington,Restaurant/Bar/Nightclub,Urban,40,Male,High School/GED,Boyfriend/Girlfriend,57.14%,12.50%,62.50%,6.67%,14.29%
165,6,2,3/25/2006,25,3,2006,Seattle,Washington,Other,Urban,28,Male,College/Trade School,Single,42.86%,12.50%,37.50%,6.67%,57.14%
166,5,0,9/23/2016,23,9,2016,Burlington,Washington,Retail,Suburban,20,Male,High School/GED,Single,71.43%,37.50%,75.00%,13.33%,42.86%
167,4,1,10/24/2014,24,10,2014,Marysville,Washington,K-12 school,Urban,15,Male,<High School,Boyfriend/Girlfriend,42.86%,37.50%,25.00%,6.67%,57.14%
168,6,4,9/2/2008,2,9,2008,Alger,Washington,Other,Rural,28,Male,NaN,Single,28.57%,37.50%,62.50%,6.67%,14.29%
169,4,0,11/29/2009,29,11,2009,Parkland,Washington,Restaurant/Bar/Nightclub,Suburban,37,Male,<High School,Married,28.57%,50.00%,37.50%,26.67%,14.29%
170,4,23,6/20/1994,20,6,1994,Spokane,Washington,Workplace,Urban,20,Male,College/Trade School,Single,0.00%,37.50%,37.50%,13.33%,28.57%

In [4]:
victims=sm_data["number_killed"].count()
# victims
states=sm_data["state"].value_counts()
# states
genders=sm_data["gender"].value_counts()
genders

Male      168
Female      3
Name: gender, dtype: int64

In [5]:
group_state=sm_data.groupby(['state'])
state_count=group_state.count().head(10)
state_count
state_avg=group_state.mean()
state_avg
state_percent=state_count/state_avg *100
# state_percent.head(15)

In [6]:
group_state["number_killed"].sum()
kill_count=group_state["number_killed"].sum()
kill_count.head()

state
Alabama         4
Alaska         18
Arizona        15
Arkansas       15
California    179
Name: number_killed, dtype: int64

In [7]:
summary = pd.DataFrame({"Number of Shootings":states, "Number of Victims Killed":kill_count})
summary.head()

shooting_summary=summary.sort_values("Number of Victims Killed", ascending=False)
shooting_summary.head(17)

                Number of Shootings  Number of Victims Killed
California                       26                       179
Texas                            18                       154
Florida                          13                       130
Nevada                            3                        66
Pennsylvania                     10                        53
Colorado                          6                        50
New York                          9                        49
North Carolina                    8                        45
Virginia                          2                        44
Connecticut                       3                        39
Washington                        8                        38
Tennessee                         3                        34
Kentucky                          5                        28
Illinois                          5                        24
Wisconsin                         4                        23
Oregon                            4                        23
Ohio                              3                        20

In [9]:
#render dataframe as html
html = shooting_summary.to_html()

In [10]:

#write html to file
text_file = open("StShootingData.html", "w")
text_file.write(html)
text_file.close()